export * from './alcohol'
export * from './dairy-food'
export * from './dish'
export * from './eat-out'
export * from './food-intake'
export * from './processed-meat'
export * from './ready-meal'
export * from './soft-drink-snack'
